package com.convex.mnotifysdk.utils

import android.content.Context

internal object PrefsHelper {
    private const val PREFS_NAME = "mnotify_prefs"
    private const val KEY_FCM_TOKEN = "fcm_token"
    private const val KEY_MNOTIFY_CONFIG = "mnotify_config"
    private const val AutoGeneratedNotification = "auto_generated_notification"

    fun saveFcmToken(context: Context, token: String) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_FCM_TOKEN, token).apply()
    }

    fun getFcmToken(context: Context): String? {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getString(KEY_FCM_TOKEN, null)
    }

    fun saveConfig(context: Context, token: String) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_MNOTIFY_CONFIG, token).apply()
    }

    fun getConfig(context: Context): String? {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getString(KEY_MNOTIFY_CONFIG, null)
    }

    fun saveAutoGeneratedNotification(context: Context, enable: Boolean) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putBoolean(AutoGeneratedNotification, enable).apply()
    }

    fun isAutoGeneratedNotification(context: Context): Boolean? {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        return prefs.getBoolean(AutoGeneratedNotification, true)
    }
}